@BeerMachineApi_HostAddress = http://localhost:5107
@noRejectUnauthorized = true

GET {{BeerMachineApi_HostAddress}}/status/machine
Accept: application/json


GET {{BeerMachineApi_HostAddress}}/status/batch
Accept: application/json


GET {{BeerMachineApi_HostAddress}}/status/inventory
Accept: application/json


POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "stop"
}
POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "reset"
}

POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "batch",
    "Parameters": {
        "id": 1,
        "amount": 50,
        "speed": 100,
        "type": 1,
        "user": 1
    }
}

POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "start"
}