@BeerMachineApi_HostAddress = http://localhost:5107
@noRejectUnauthorized = true

GET {{BeerMachineApi_HostAddress}}/machine/status
Accept: application/json

###

POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "stop"
}
POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "reset"
}

POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "batch",
    "Parameters": {
        "id": 1,
        "amount": 20,
        "speed": 100,
        "type": 1
    }
}

POST {{BeerMachineApi_HostAddress}}/machine/command HTTP/1.1
Content-Type: application/json
{
    "Type": "start"
}